"""Public, token-gated, read-only catalog of published parts.

This router is intentionally NOT mounted under /api and NOT gated by
require_member_for_writes — anyone with the URL gets to read.
"""
from __future__ import annotations

from html import escape

from fastapi import APIRouter, HTTPException, status
from fastapi.responses import HTMLResponse
from sqlalchemy import select

from app.core.deps import DbSession
from app.core.responses import ok
from app.domain.parts.models import Part
from app.domain.workspaces.models import Workspace

router = APIRouter()


def _resolve_workspace(db, token: str) -> Workspace:
    """Match the token to an enabled workspace, or 404."""
    if not token:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="catalog not found")
    ws = (
        db.execute(
            select(Workspace).where(
                Workspace.catalog_token == token,
                Workspace.catalog_enabled.is_(True),
            )
        )
        .scalars()
        .first()
    )
    if not ws:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="catalog not found")
    return ws


def _published_parts(db, workspace_id) -> list[Part]:
    return list(
        db.execute(
            select(Part)
            .where(Part.workspace_id == workspace_id)
            .where(Part.archived_at.is_(None))
            .where(Part.published.is_(True))
            .order_by(Part.name)
        ).scalars()
    )


def _part_dict(p: Part) -> dict:
    return {
        "id": str(p.id),
        "name": p.name,
        "manufacturer": p.manufacturer,
        "mpn": p.mpn,
        "footprint": p.footprint,
        "description": p.description,
    }


# Tiny inline CSS keeps the page self-contained — no template engine, no static
# pipeline, no JS. The page is a leaf endpoint that needs to render once.
_PAGE_CSS = """
* { box-sizing: border-box; }
body {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
  background: #f7f7f8;
  color: #18181b;
  margin: 0;
  padding: 2rem 1.25rem;
}
.wrap { max-width: 960px; margin: 0 auto; }
header { border-bottom: 1px solid #e4e4e7; padding-bottom: 1rem; margin-bottom: 1.25rem; }
.brand {
  font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
  font-size: 0.85rem;
  color: #71717a;
  letter-spacing: 0.02em;
}
h1 { font-size: 1.5rem; margin: 0.25rem 0 0.5rem; }
.lead { color: #52525b; font-size: 0.95rem; margin: 0; }
table { width: 100%; border-collapse: collapse; background: #fff; border: 1px solid #e4e4e7; border-radius: 6px; overflow: hidden; }
th, td { text-align: left; padding: 0.6rem 0.8rem; font-size: 0.9rem; vertical-align: top; }
th { background: #fafafa; font-weight: 600; color: #3f3f46; border-bottom: 1px solid #e4e4e7; }
tr + tr td { border-top: 1px solid #f1f1f3; }
td.mono { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: 0.85rem; color: #3f3f46; }
.empty { color: #71717a; font-style: italic; padding: 1.5rem; text-align: center; background: #fff; border: 1px dashed #d4d4d8; border-radius: 6px; }
footer { color: #a1a1aa; font-size: 0.8rem; margin-top: 1.5rem; }
"""


def _render_html(ws: Workspace, parts: list[Part]) -> str:
    name = escape(ws.name)
    brand = f"stockmgr · {name} catalog"
    rows = []
    for p in parts:
        rows.append(
            "<tr>"
            f"<td>{escape(p.name or '')}</td>"
            f"<td>{escape(p.manufacturer or '')}</td>"
            f"<td class='mono'>{escape(p.mpn or '')}</td>"
            f"<td>{escape(p.footprint or '')}</td>"
            f"<td>{escape(p.description or '')}</td>"
            "</tr>"
        )
    table = (
        "<table><thead><tr>"
        "<th>Name</th><th>Manufacturer</th><th>MPN</th><th>Footprint</th><th>Description</th>"
        "</tr></thead><tbody>"
        + "".join(rows)
        + "</tbody></table>"
    ) if rows else "<div class='empty'>No published parts yet.</div>"
    return (
        "<!doctype html>"
        "<html lang='en'><head>"
        "<meta charset='utf-8'>"
        "<meta name='viewport' content='width=device-width,initial-scale=1'>"
        "<meta name='robots' content='noindex,nofollow'>"
        f"<title>{brand}</title>"
        f"<style>{_PAGE_CSS}</style>"
        "</head><body><div class='wrap'>"
        "<header>"
        f"<div class='brand'>{escape(brand)}</div>"
        f"<h1>{name}</h1>"
        "<p class='lead'>Public read-only catalog of parts this workspace has chosen to publish.</p>"
        "</header>"
        f"{table}"
        "<footer>Generated by stockmgr · This page is publicly accessible to anyone with the link.</footer>"
        "</div></body></html>"
    )


@router.get("/{token}", response_class=HTMLResponse)
def catalog_html(token: str, db: DbSession):
    ws = _resolve_workspace(db, token)
    parts = _published_parts(db, ws.id)
    return HTMLResponse(content=_render_html(ws, parts), status_code=200)


@router.get("/{token}/parts.json")
def catalog_json(token: str, db: DbSession):
    ws = _resolve_workspace(db, token)
    parts = _published_parts(db, ws.id)
    return ok(
        {
            "workspace": {"id": str(ws.id), "name": ws.name},
            "parts": [_part_dict(p) for p in parts],
        }
    )
