"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-04-28 19:14:05.605721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=500), nullable=False),
    sa.Column('locale', sa.String(length=20), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('user_sessions',
    sa.Column('token', sa.String(length=120), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('workspaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('currency_default', sa.String(length=3), nullable=False),
    sa.Column('lot_control_enabled', sa.Boolean(), nullable=False),
    sa.Column('serial_tracking_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attachments',
    sa.Column('object_type', sa.String(length=40), nullable=False),
    sa.Column('object_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=400), nullable=False),
    sa.Column('file_type', sa.String(length=40), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('storage_key', sa.String(length=800), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_attach_object', 'attachments', ['workspace_id', 'object_type', 'object_id'], unique=False)
    op.create_index(op.f('ix_attachments_archived_at'), 'attachments', ['archived_at'], unique=False)
    op.create_index(op.f('ix_attachments_workspace_id'), 'attachments', ['workspace_id'], unique=False)
    op.create_table('bom_import_presets',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('config_json', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bom_import_presets_archived_at'), 'bom_import_presets', ['archived_at'], unique=False)
    op.create_index(op.f('ix_bom_import_presets_workspace_id'), 'bom_import_presets', ['workspace_id'], unique=False)
    op.create_table('custom_fields',
    sa.Column('object_type', sa.String(length=40), nullable=False),
    sa.Column('object_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=256), nullable=False),
    sa.Column('value', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'object_type', 'object_id', 'key', name='uq_cf_unique')
    )
    op.create_index('ix_cf_object', 'custom_fields', ['workspace_id', 'object_type', 'object_id'], unique=False)
    op.create_index(op.f('ix_custom_fields_archived_at'), 'custom_fields', ['archived_at'], unique=False)
    op.create_index(op.f('ix_custom_fields_workspace_id'), 'custom_fields', ['workspace_id'], unique=False)
    op.create_table('projects',
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes_markdown', sa.Text(), nullable=True),
    sa.Column('associated_subassembly_part_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['associated_subassembly_part_id'], ['parts.id'], name='fk_projects_associated_subassembly_part', ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_archived_at'), 'projects', ['archived_at'], unique=False)
    op.create_index(op.f('ix_projects_workspace_id'), 'projects', ['workspace_id'], unique=False)
    op.create_index('ix_projects_ws_archived', 'projects', ['workspace_id', 'archived_at'], unique=False)
    op.create_index('ix_projects_ws_name', 'projects', ['workspace_id', 'name'], unique=False)
    op.create_table('storage_locations',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('single_part_only', sa.Boolean(), nullable=False),
    sa.Column('existing_parts_only', sa.Boolean(), nullable=False),
    sa.Column('is_full', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'name', name='uq_storage_ws_name')
    )
    op.create_index(op.f('ix_storage_locations_archived_at'), 'storage_locations', ['archived_at'], unique=False)
    op.create_index(op.f('ix_storage_locations_workspace_id'), 'storage_locations', ['workspace_id'], unique=False)
    op.create_index('ix_storage_ws_archived', 'storage_locations', ['workspace_id', 'archived_at'], unique=False)
    op.create_table('tags',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'name', name='uq_tag_ws_name')
    )
    op.create_index(op.f('ix_tags_archived_at'), 'tags', ['archived_at'], unique=False)
    op.create_index(op.f('ix_tags_workspace_id'), 'tags', ['workspace_id'], unique=False)
    op.create_table('workspace_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'user_id', name='uq_workspace_member')
    )
    op.create_index(op.f('ix_workspace_members_user_id'), 'workspace_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_workspace_members_workspace_id'), 'workspace_members', ['workspace_id'], unique=False)
    op.create_table('parts',
    sa.Column('part_type', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('internal_part_number', sa.String(length=120), nullable=True),
    sa.Column('manufacturer', sa.String(length=200), nullable=True),
    sa.Column('mpn', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes_markdown', sa.Text(), nullable=True),
    sa.Column('footprint', sa.String(length=120), nullable=True),
    sa.Column('linked_external_id', sa.String(length=200), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('low_stock_report_quantity', sa.Integer(), nullable=True),
    sa.Column('attrition_percentage', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('attrition_min_quantity', sa.Integer(), nullable=False),
    sa.Column('default_storage_location_id', sa.UUID(), nullable=True),
    sa.Column('default_storage_mandatory', sa.Boolean(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['default_storage_location_id'], ['storage_locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parts_archived_at'), 'parts', ['archived_at'], unique=False)
    op.create_index(op.f('ix_parts_workspace_id'), 'parts', ['workspace_id'], unique=False)
    op.create_index('ix_parts_ws_archived', 'parts', ['workspace_id', 'archived_at'], unique=False)
    op.create_index('ix_parts_ws_ipn', 'parts', ['workspace_id', 'internal_part_number'], unique=False)
    op.create_index('ix_parts_ws_mpn', 'parts', ['workspace_id', 'manufacturer', 'mpn'], unique=False)
    op.create_index('ix_parts_ws_name', 'parts', ['workspace_id', 'name'], unique=False)
    op.create_table('tag_links',
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.Column('object_type', sa.String(length=40), nullable=False),
    sa.Column('object_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'tag_id', 'object_type', 'object_id', name='uq_tag_link')
    )
    op.create_index('ix_tag_link_object', 'tag_links', ['workspace_id', 'object_type', 'object_id'], unique=False)
    op.create_index(op.f('ix_tag_links_archived_at'), 'tag_links', ['archived_at'], unique=False)
    op.create_index(op.f('ix_tag_links_workspace_id'), 'tag_links', ['workspace_id'], unique=False)
    op.create_table('lots',
    sa.Column('part_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('serial_number', sa.String(length=200), nullable=True),
    sa.Column('parent_lot_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_order_id', sa.UUID(), nullable=True),
    sa.Column('source_build_id', sa.UUID(), nullable=True),
    sa.Column('purchase_quantity', sa.Integer(), nullable=True),
    sa.Column('purchase_unit_cost', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('purchase_currency', sa.String(length=3), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_lot_id'], ['lots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lots_archived_at'), 'lots', ['archived_at'], unique=False)
    op.create_index(op.f('ix_lots_part_id'), 'lots', ['part_id'], unique=False)
    op.create_index(op.f('ix_lots_serial_number'), 'lots', ['serial_number'], unique=False)
    op.create_index(op.f('ix_lots_workspace_id'), 'lots', ['workspace_id'], unique=False)
    op.create_index('ix_lots_ws_archived', 'lots', ['workspace_id', 'archived_at'], unique=False)
    op.create_index('ix_lots_ws_part', 'lots', ['workspace_id', 'part_id'], unique=False)
    op.create_table('part_cad_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('part_id', sa.UUID(), nullable=False),
    sa.Column('cad_key', sa.String(length=300), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_part_cad_keys_cad_key'), 'part_cad_keys', ['cad_key'], unique=False)
    op.create_index(op.f('ix_part_cad_keys_part_id'), 'part_cad_keys', ['part_id'], unique=False)
    op.create_table('part_meta_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meta_part_id', sa.UUID(), nullable=False),
    sa.Column('part_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['meta_part_id'], ['parts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meta_part_id', 'part_id', name='uq_meta_member')
    )
    op.create_index(op.f('ix_part_meta_members_meta_part_id'), 'part_meta_members', ['meta_part_id'], unique=False)
    op.create_index(op.f('ix_part_meta_members_part_id'), 'part_meta_members', ['part_id'], unique=False)
    op.create_table('part_substitutes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('part_id', sa.UUID(), nullable=False),
    sa.Column('substitute_part_id', sa.UUID(), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['substitute_part_id'], ['parts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('part_id', 'substitute_part_id', name='uq_part_sub')
    )
    op.create_index(op.f('ix_part_substitutes_part_id'), 'part_substitutes', ['part_id'], unique=False)
    op.create_index(op.f('ix_part_substitutes_substitute_part_id'), 'part_substitutes', ['substitute_part_id'], unique=False)
    op.create_table('project_entries',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('entry_type', sa.String(length=20), nullable=False),
    sa.Column('part_id', sa.UUID(), nullable=True),
    sa.Column('meta_part_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('designators', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('cad_footprint', sa.String(length=120), nullable=True),
    sa.Column('cad_key', sa.String(length=300), nullable=True),
    sa.Column('dnp', sa.Boolean(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['meta_part_id'], ['parts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_entries_archived_at'), 'project_entries', ['archived_at'], unique=False)
    op.create_index('ix_project_entries_part', 'project_entries', ['workspace_id', 'part_id'], unique=False)
    op.create_index('ix_project_entries_proj', 'project_entries', ['workspace_id', 'project_id'], unique=False)
    op.create_index(op.f('ix_project_entries_workspace_id'), 'project_entries', ['workspace_id'], unique=False)
    op.create_table('stock_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('part_id', sa.UUID(), nullable=False),
    sa.Column('lot_id', sa.UUID(), nullable=True),
    sa.Column('storage_location_id', sa.UUID(), nullable=True),
    sa.Column('quantity_delta', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('operation_type', sa.String(length=40), nullable=False),
    sa.Column('related_entry_id', sa.UUID(), nullable=True),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('order_entry_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('build_id', sa.UUID(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_entry_id'], ['stock_entries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['storage_location_id'], ['storage_locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_stock_ws_lot', 'stock_entries', ['workspace_id', 'lot_id'], unique=False)
    op.create_index('ix_stock_ws_occurred', 'stock_entries', ['workspace_id', 'occurred_at'], unique=False)
    op.create_index('ix_stock_ws_part_status', 'stock_entries', ['workspace_id', 'part_id', 'status'], unique=False)
    op.create_index('ix_stock_ws_storage', 'stock_entries', ['workspace_id', 'storage_location_id'], unique=False)
    # Deferred FK to break the parts<->projects circular dependency.
    op.create_foreign_key(
        'fk_projects_associated_subassembly_part',
        'projects', 'parts',
        ['associated_subassembly_part_id'], ['id'],
        ondelete='SET NULL', use_alter=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_projects_associated_subassembly_part', 'projects', type_='foreignkey')
    op.drop_index('ix_stock_ws_storage', table_name='stock_entries')
    op.drop_index('ix_stock_ws_part_status', table_name='stock_entries')
    op.drop_index('ix_stock_ws_occurred', table_name='stock_entries')
    op.drop_index('ix_stock_ws_lot', table_name='stock_entries')
    op.drop_table('stock_entries')
    op.drop_index(op.f('ix_project_entries_workspace_id'), table_name='project_entries')
    op.drop_index('ix_project_entries_proj', table_name='project_entries')
    op.drop_index('ix_project_entries_part', table_name='project_entries')
    op.drop_index(op.f('ix_project_entries_archived_at'), table_name='project_entries')
    op.drop_table('project_entries')
    op.drop_index(op.f('ix_part_substitutes_substitute_part_id'), table_name='part_substitutes')
    op.drop_index(op.f('ix_part_substitutes_part_id'), table_name='part_substitutes')
    op.drop_table('part_substitutes')
    op.drop_index(op.f('ix_part_meta_members_part_id'), table_name='part_meta_members')
    op.drop_index(op.f('ix_part_meta_members_meta_part_id'), table_name='part_meta_members')
    op.drop_table('part_meta_members')
    op.drop_index(op.f('ix_part_cad_keys_part_id'), table_name='part_cad_keys')
    op.drop_index(op.f('ix_part_cad_keys_cad_key'), table_name='part_cad_keys')
    op.drop_table('part_cad_keys')
    op.drop_index('ix_lots_ws_part', table_name='lots')
    op.drop_index('ix_lots_ws_archived', table_name='lots')
    op.drop_index(op.f('ix_lots_workspace_id'), table_name='lots')
    op.drop_index(op.f('ix_lots_serial_number'), table_name='lots')
    op.drop_index(op.f('ix_lots_part_id'), table_name='lots')
    op.drop_index(op.f('ix_lots_archived_at'), table_name='lots')
    op.drop_table('lots')
    op.drop_index(op.f('ix_tag_links_workspace_id'), table_name='tag_links')
    op.drop_index(op.f('ix_tag_links_archived_at'), table_name='tag_links')
    op.drop_index('ix_tag_link_object', table_name='tag_links')
    op.drop_table('tag_links')
    op.drop_index('ix_parts_ws_name', table_name='parts')
    op.drop_index('ix_parts_ws_mpn', table_name='parts')
    op.drop_index('ix_parts_ws_ipn', table_name='parts')
    op.drop_index('ix_parts_ws_archived', table_name='parts')
    op.drop_index(op.f('ix_parts_workspace_id'), table_name='parts')
    op.drop_index(op.f('ix_parts_archived_at'), table_name='parts')
    op.drop_table('parts')
    op.drop_index(op.f('ix_workspace_members_workspace_id'), table_name='workspace_members')
    op.drop_index(op.f('ix_workspace_members_user_id'), table_name='workspace_members')
    op.drop_table('workspace_members')
    op.drop_index(op.f('ix_tags_workspace_id'), table_name='tags')
    op.drop_index(op.f('ix_tags_archived_at'), table_name='tags')
    op.drop_table('tags')
    op.drop_index('ix_storage_ws_archived', table_name='storage_locations')
    op.drop_index(op.f('ix_storage_locations_workspace_id'), table_name='storage_locations')
    op.drop_index(op.f('ix_storage_locations_archived_at'), table_name='storage_locations')
    op.drop_table('storage_locations')
    op.drop_index('ix_projects_ws_name', table_name='projects')
    op.drop_index('ix_projects_ws_archived', table_name='projects')
    op.drop_index(op.f('ix_projects_workspace_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_archived_at'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_custom_fields_workspace_id'), table_name='custom_fields')
    op.drop_index(op.f('ix_custom_fields_archived_at'), table_name='custom_fields')
    op.drop_index('ix_cf_object', table_name='custom_fields')
    op.drop_table('custom_fields')
    op.drop_index(op.f('ix_bom_import_presets_workspace_id'), table_name='bom_import_presets')
    op.drop_index(op.f('ix_bom_import_presets_archived_at'), table_name='bom_import_presets')
    op.drop_table('bom_import_presets')
    op.drop_index(op.f('ix_attachments_workspace_id'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_archived_at'), table_name='attachments')
    op.drop_index('ix_attach_object', table_name='attachments')
    op.drop_table('attachments')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
