"""orders + order_entries

Revision ID: 0002
Revises: 0001
Create Date: 2026-04-28
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('order_type', sa.String(length=20), nullable=False),
    sa.Column('supplier', sa.String(length=300), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('ordered_on', sa.Date(), nullable=True),
    sa.Column('expected_on', sa.Date(), nullable=True),
    sa.Column('received_on', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_archived_at'), 'orders', ['archived_at'], unique=False)
    op.create_index(op.f('ix_orders_workspace_id'), 'orders', ['workspace_id'], unique=False)
    op.create_index('ix_orders_ws_archived', 'orders', ['workspace_id', 'archived_at'], unique=False)
    op.create_index('ix_orders_ws_status', 'orders', ['workspace_id', 'status'], unique=False)
    op.create_table('order_entries',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('part_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=True),
    sa.Column('quantity_ordered', sa.Integer(), nullable=False),
    sa.Column('quantity_received', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_entries_archived_at'), 'order_entries', ['archived_at'], unique=False)
    op.create_index('ix_order_entries_order', 'order_entries', ['workspace_id', 'order_id'], unique=False)
    op.create_index('ix_order_entries_part', 'order_entries', ['workspace_id', 'part_id'], unique=False)
    op.create_index(op.f('ix_order_entries_workspace_id'), 'order_entries', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_entries_workspace_id'), table_name='order_entries')
    op.drop_index('ix_order_entries_part', table_name='order_entries')
    op.drop_index('ix_order_entries_order', table_name='order_entries')
    op.drop_index(op.f('ix_order_entries_archived_at'), table_name='order_entries')
    op.drop_table('order_entries')
    op.drop_index('ix_orders_ws_status', table_name='orders')
    op.drop_index('ix_orders_ws_archived', table_name='orders')
    op.drop_index(op.f('ix_orders_workspace_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_archived_at'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
