"""builds

Revision ID: 0003
Revises: 0002
Create Date: 2026-04-28
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('builds',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('output_lot_id', sa.UUID(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['output_lot_id'], ['lots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_builds_archived_at'), 'builds', ['archived_at'], unique=False)
    op.create_index(op.f('ix_builds_workspace_id'), 'builds', ['workspace_id'], unique=False)
    op.create_index('ix_builds_ws_archived', 'builds', ['workspace_id', 'archived_at'], unique=False)
    op.create_index('ix_builds_ws_project', 'builds', ['workspace_id', 'project_id'], unique=False)
    op.create_index('ix_builds_ws_status', 'builds', ['workspace_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_builds_ws_status', table_name='builds')
    op.drop_index('ix_builds_ws_project', table_name='builds')
    op.drop_index('ix_builds_ws_archived', table_name='builds')
    op.drop_index(op.f('ix_builds_workspace_id'), table_name='builds')
    op.drop_index(op.f('ix_builds_archived_at'), table_name='builds')
    op.drop_table('builds')
    # ### end Alembic commands ###
